### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by cwhuang888** [tianbaochou/NasUnet#2]
Hi,

First of all, thanks for sharing your code which is a great benefit for us to experiment more ideas.

However, on a GTX 1080 8GB card, I have encountered a Runtime Error CUDA OOM issue
When executing the following:
      python3 train.py --config ../configs/nas_unet/nas_unet_voc.yml 
even reducing the batch_size to 1 would not help.

Could you give some suggestions to resolve this?

Thank you !

**Comment by tianbaochou** [comment]
I use the Titan pascalx 12GB and the batch_size = 2~4 will  be ok when the image size is 480x480, but 10~16 when image size is 256x256.   Do you work in windows or ubuntu?, you can check the gpu used: `nvidia-smi`. if you don't have solved this problem. You can show me the detailed information(error log et, al). good luck!

**Comment by tianbaochou** [comment]
> Hi,
> 
> First of all, thanks for sharing your code which is a great benefit for us to experiment more ideas.
> 
> However, on a GTX 1080 8GB card, I have encountered a Runtime Error CUDA OOM issue
> When executing the following:
> python3 train.py --config ../configs/nas_unet/nas_unet_voc.yml
> even reducing the batch_size to 1 would not help.
> 
> Could you give some suggestions to resolve this?
> 
> Thank you !

I use the Titan pascalx 12GB and the batch_size = 2-4 will  be ok, when the image size is 480x480, but 10-16 when image size is 256x256.   Do you work in windows or ubuntu?, you can check the gpu used: `nvidia-smi`. if you don't have solved this problem. You can show me the detailed information(error log et, al). good luck!

**Comment by cwhuang888** [comment]
Thank you for replying.
My environment is Ubuntu.

The problem still occurs even reducing VOC dataset  image size from 256x56 to 16x16 as shown following (please correct me if i have modified the wrong place):
BaseDataset: crop_size 16

During the execution, the memory usage of the GPU rises quickly from 526MiB to 8028MiB and stopped.
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
|  0      35C    P2    44W / 240W |    526MiB /  8116MiB |      2%      Default |
|  0      36C    P2    54W / 240W |   8028MiB /  8116MiB |      0%      Default |

It seems to me the model is occupying large amount of memory regardless of the image size.

Complete  running info as follow:
Usage model :nasunet
Experiment dir: ../logs/nasunet/train/pascal_voc/20190425-155153
RUNDIR: ../logs/nasunet/train/pascal_voc/20190425-155153
04/25 03:51:53 PM nasunet-Train
BaseDataset: crop_size 16
2913it [00:00, 4463.23it/s]
1449it [00:00, 46167.23it/s]
dataset weights: None
Using loss: cross_entropy
04/25 03:51:54 PM Using loss SegmentationLosses()
This model does not need pretrained backbone
04/25 03:52:57 PM Initialize the model weights: kaiming_uniform
04/25 03:52:57 PM gpu device = 0
Traceback (most recent call last):
  File "train.py", line 454, in <module>
    train_network = Network()
  File "train.py", line 33, in __init__
    self._init_model()
  File "train.py", line 160, in _init_model
    self.model = model.to(self.device)
  File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 576.00 MiB (GPU 0; 7.93 GiB total capacity; 7.25 GiB already allocated; 87.50 MiB free; 207.00 KiB cached)

**Comment by tianbaochou** [comment]
> Thank you for replying.
> My environment is Ubuntu.
> 
> The problem still occurs even reducing VOC dataset image size from 256x56 to 16x16 as shown following (please correct me if i have modified the wrong place):
> BaseDataset: crop_size 16
> 
> During the execution, the memory usage of the GPU rises quickly from 526MiB to 8028MiB and stopped.
> | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> | 0 35C P2 44W / 240W | 526MiB / 8116MiB | 2% Default |
> | 0 36C P2 54W / 240W | 8028MiB / 8116MiB | 0% Default |
> 
> It seems to me the model is occupying large amount of memory regardless of the image size.
> 
> Complete running info as follow:
> Usage model :nasunet
> Experiment dir: ../logs/nasunet/train/pascal_voc/20190425-155153
> RUNDIR: ../logs/nasunet/train/pascal_voc/20190425-155153
> 04/25 03:51:53 PM nasunet-Train
> BaseDataset: crop_size 16
> 2913it [00:00, 4463.23it/s]
> 1449it [00:00, 46167.23it/s]
> dataset weights: None
> Using loss: cross_entropy
> 04/25 03:51:54 PM Using loss SegmentationLosses()
> This model does not need pretrained backbone
> 04/25 03:52:57 PM Initialize the model weights: kaiming_uniform
> 04/25 03:52:57 PM gpu device = 0
> Traceback (most recent call last):
> File "train.py", line 454, in 
> train_network = Network()
> File "train.py", line 33, in **init**
> self._init_model()
> File "train.py", line 160, in _init_model
> self.model = model.to(self.device)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in to
> return self._apply(convert)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
> module._apply(fn)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
> module._apply(fn)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
> module._apply(fn)
> [Previous line repeated 2 more times]
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
> param.data = fn(param.data)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 379, in convert
> return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
> RuntimeError: CUDA out of memory. Tried to allocate 576.00 MiB (GPU 0; 7.93 GiB total capacity; 7.25 GiB already allocated; 87.50 MiB free; 207.00 KiB cached)

Hi, I add new feature for NasU-net, and test on my workstation with 4GB nvidia gpu, Quadro K2200. the crop size is 256 and batch size is 2. It cost 3.4GB gpu memory. I test it in win10.  Can you test code in you  environment again? thanks you.

**Comment by tianbaochou** [comment]
> Thank you for replying.
> My environment is Ubuntu.
> 
> The problem still occurs even reducing VOC dataset image size from 256x56 to 16x16 as shown following (please correct me if i have modified the wrong place):
> BaseDataset: crop_size 16
> 
> During the execution, the memory usage of the GPU rises quickly from 526MiB to 8028MiB and stopped.
> | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> | 0 35C P2 44W / 240W | 526MiB / 8116MiB | 2% Default |
> | 0 36C P2 54W / 240W | 8028MiB / 8116MiB | 0% Default |
> 
> It seems to me the model is occupying large amount of memory regardless of the image size.
> 
> Complete running info as follow:
> Usage model :nasunet
> Experiment dir: ../logs/nasunet/train/pascal_voc/20190425-155153
> RUNDIR: ../logs/nasunet/train/pascal_voc/20190425-155153
> 04/25 03:51:53 PM nasunet-Train
> BaseDataset: crop_size 16
> 2913it [00:00, 4463.23it/s]
> 1449it [00:00, 46167.23it/s]
> dataset weights: None
> Using loss: cross_entropy
> 04/25 03:51:54 PM Using loss SegmentationLosses()
> This model does not need pretrained backbone
> 04/25 03:52:57 PM Initialize the model weights: kaiming_uniform
> 04/25 03:52:57 PM gpu device = 0
> Traceback (most recent call last):
> File "train.py", line 454, in 
> train_network = Network()
> File "train.py", line 33, in **init**
> self._init_model()
> File "train.py", line 160, in _init_model
> self.model = model.to(self.device)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in to
> return self._apply(convert)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
> module._apply(fn)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
> module._apply(fn)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
> module._apply(fn)
> [Previous line repeated 2 more times]
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
> param.data = fn(param.data)
> File "/home/cwhuang/anaconda3/envs/nas_unet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 379, in convert
> return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
> RuntimeError: CUDA out of memory. Tried to allocate 576.00 MiB (GPU 0; 7.93 GiB total capacity; 7.25 GiB already allocated; 87.50 MiB free; 207.00 KiB cached)

I fixed the configure files and you can see the details for solving CUDA OOM problems in README. thanks!.

**Comment by cwhuang888** [comment]
Thank you for helping out, the issue is gone now!

**Comment by skrish13** [comment]
Hi, @cwhuang888 @tianbaochou, I was curious roughly how big the model/weights were in case you remember? (10MB/100MB/etc?)
